server:
  port: 8080

spring:
  shardingsphere:
    datasource:
      names: ds0,ds1
      ds0:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/sharding?characterEncoding=utf-8
        username: root
        password: 123456
      ds1:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://192.168.1.231:3306/Test?characterEncoding=utf-8
        username: root
        password: Zs@123456
    sharding:
      tables:
        user:
          actual-data-nodes: ds$->{0..1}.user$->{0..1} #数据节点
          #table-strategy:
          #  inline:
          #    sharding-column: user_id
          #    algorithm-expression: user$->{user_id % 2}
          database-strategy:  #分库策略
            standard:
              sharding-column: id
              precise-algorithm-class-name: com.example.sharding.common.algorithm.MyPreciseDBShardingAlgorithm
          tableStrategy:
            standard:
              shardingColumn: user_id
              preciseAlgorithmClassName: com.example.sharding.common.algorithm.MyPreciseTableShardingAlgorithm
          key-generator:
            column: user_id
            type: SNOWFLAKE
